let
    Fonte = SharePoint.Tables("https://agcapitalconsultoria.sharepoint.com/sites/Jurdicocontencioso", [ApiVersion = 15]),
    #"6550e5f4-b2e9-4473-94cc-8fc5af56cf4d" = Fonte{[Id="6550e5f4-b2e9-4473-94cc-8fc5af56cf4d"]}[Items],
    #"Colunas Renomeadas" = Table.RenameColumns(#"6550e5f4-b2e9-4473-94cc-8fc5af56cf4d",{{"ID", "ID.1"}, {"field_1", "Área"}, {"field_2", "AGente"}, {"field_3", "Assunto"}, {"Title", "Linha"}, {"field_4", "Descrição"}, {"Dataehora", "Data da ssugestão"}, {"field_7", "Status"}, {"Datadaimplementação", "Início Análise"}}),
    #"Colunas Removidas" = Table.RemoveColumns(#"Colunas Renomeadas",{"FileSystemObjectType", "ServerRedirectedEmbedUri", "ServerRedirectedEmbedUrl", "ContentTypeId", "Id", "OData__ColorTag", "ComplianceAssetId"}),
    #"Colunas Renomeadas1" = Table.RenameColumns(#"Colunas Removidas",{{"Data da ssugestão", "Data da sugestão"}}),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas1",{{"Data da sugestão", type date}}),
    #"Colunas Removidas1" = Table.RemoveColumns(#"Tipo Alterado",{"AverageRating", "RatingCount", "RatedByStringId", "LikedByStringId"}),
    #"Colunas Reordenadas" = Table.ReorderColumns(#"Colunas Removidas1",{"Linha", "Área", "AGente", "Assunto", "Descrição", "Data da sugestão", "LikesCount", "Status", "Votos", "Início Análise", "DataInícioAnálise", "DataAprovação", "DataInícioImplementa_x00e7", "Priorização", "ID.1", "Modified", "Created", "AuthorId", "EditorId", "OData__UIVersionString", "Attachments", "GUID", "FirstUniqueAncestorSecurableObject", "RoleAssignments", "AttachmentFiles", "ContentType", "GetDlpPolicyTip", "FieldValuesAsHtml", "FieldValuesAsText", "FieldValuesForEdit", "File", "Folder", "LikedByInformation", "ParentList", "Properties", "Versions", "RatedBy", "LikedBy", "Author", "Editor"}),
    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Reordenadas",{{"LikesCount", Int64.Type}, {"Votos", Int64.Type}, {"Início Análise", type date}}),
    #"Valor Substituído" = Table.ReplaceValue(#"Tipo Alterado1",null,"",Replacer.ReplaceValue,{"Priorização"}),
    #"Colunas Renomeadas2" = Table.RenameColumns(#"Valor Substituído",{{"Início Análise", "Em desenvolvimento"}}),
    #"Colunas Reordenadas1" = Table.ReorderColumns(#"Colunas Renomeadas2",{"Linha", "Área", "AGente", "Assunto", "Descrição", "Data da sugestão", "LikesCount", "Status", "Votos", "DataInícioAnálise", "DataAprovação", "Em desenvolvimento", "DataInícioImplementa_x00e7", "Priorização", "ID.1", "Modified", "Created", "AuthorId", "EditorId", "OData__UIVersionString", "Attachments", "GUID", "FirstUniqueAncestorSecurableObject", "RoleAssignments", "AttachmentFiles", "ContentType", "GetDlpPolicyTip", "FieldValuesAsHtml", "FieldValuesAsText", "FieldValuesForEdit", "File", "Folder", "LikedByInformation", "ParentList", "Properties", "Versions", "RatedBy", "LikedBy", "Author", "Editor"}),
    #"Colunas Renomeadas3" = Table.RenameColumns(#"Colunas Reordenadas1",{{"DataInícioAnálise", "Início Análise"}}),
    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Colunas Renomeadas3",{{"Início Análise", type date}}),
    #"Colunas Renomeadas4" = Table.RenameColumns(#"Tipo Alterado2",{{"DataInícioImplementa_x00e7", "Conclusão"}, {"DataAprovação", "Aprovação"}}),
    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Colunas Renomeadas4",{{"Aprovação", type date}, {"Conclusão", type date}}),
    #"Colunas Reordenadas2" = Table.ReorderColumns(#"Tipo Alterado3",{"Linha", "Área", "AGente", "Assunto", "Descrição", "Data da sugestão", "LikesCount", "Status", "Priorização", "Votos", "Início Análise", "Aprovação", "Em desenvolvimento", "Conclusão", "ID.1", "Modified", "Created", "AuthorId", "EditorId", "OData__UIVersionString", "Attachments", "GUID", "FirstUniqueAncestorSecurableObject", "RoleAssignments", "AttachmentFiles", "ContentType", "GetDlpPolicyTip", "FieldValuesAsHtml", "FieldValuesAsText", "FieldValuesForEdit", "File", "Folder", "LikedByInformation", "ParentList", "Properties", "Versions", "RatedBy", "LikedBy", "Author", "Editor"}),
    #"Colunas Renomeadas5" = Table.RenameColumns(#"Colunas Reordenadas2",{{"Conclusão", "Em desenvolvimento"}, {"Em desenvolvimento", "Conclusão"}}),
    #"Colunas Reordenadas3" = Table.ReorderColumns(#"Colunas Renomeadas5",{"Linha", "Área", "AGente", "Assunto", "Descrição", "Data da sugestão", "LikesCount", "Status", "Priorização", "Votos", "Início Análise", "Aprovação", "Em desenvolvimento", "Conclusão", "ID.1", "Modified", "Created", "AuthorId", "EditorId", "OData__UIVersionString", "Attachments", "GUID", "FirstUniqueAncestorSecurableObject", "RoleAssignments", "AttachmentFiles", "ContentType", "GetDlpPolicyTip", "FieldValuesAsHtml", "FieldValuesAsText", "FieldValuesForEdit", "File", "Folder", "LikedByInformation", "ParentList", "Properties", "Versions", "RatedBy", "LikedBy", "Author", "Editor"}),
    #"Colunas Removidas2" = Table.RemoveColumns(#"Colunas Reordenadas3",{"ID.1"})
in
    #"Colunas Removidas2"
